### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by huangsir0** [liranhao/recognition_qrcode#17]
``` dart
D/HwGalleryCacheManagerImpl(32315): mIsEffect:false
I/tflite  (32315): Initialized TensorFlow Lite runtime.
W/libc    (32315): Access denied finding property "ro.hardware.chipname"
I/tflite  (32315): Created TensorFlow Lite XNNPACK delegate for CPU.
I/native  (32315): I0000 00:00:1692339180.194213   32497 oned_decoder_client.cc:695] barhopper::deep_learning::OnedDecoderClient is created successfully.
D/AndroidRuntime(32315): Shutting down VM
E/AndroidRuntime(32315): FATAL EXCEPTION: main
E/AndroidRuntime(32315): Process: com.wawavenet.walang, PID: 32315
E/AndroidRuntime(32315): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/mlkit/vision/barcode/Barcode;
E/AndroidRuntime(32315): 	at com.recognition.qrcode.recognition_qrcode.RecognitionQrcodePlugin$3.onSuccess(RecognitionQrcodePlugin.java:161)
E/AndroidRuntime(32315): 	at com.recognition.qrcode.recognition_qrcode.RecognitionQrcodePlugin$3.onSuccess(RecognitionQrcodePlugin.java:155)
E/AndroidRuntime(32315): 	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
E/AndroidRuntime(32315): 	at android.os.Handler.handleCallback(Handler.java:955)
E/AndroidRuntime(32315): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(32315): 	at android.os.Looper.loopOnce(Looper.java:206)
E/AndroidRuntime(32315): 	at android.os.Looper.loop(Looper.java:296)
E/AndroidRuntime(32315): 	at android.app.ActivityThread.main(ActivityThread.java:9000)
E/AndroidRuntime(32315): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32315): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
E/AndroidRuntime(32315): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:976)
E/AndroidRuntime(32315): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.mlkit.vision.barcode.Barcode" on path: DexPathList[[zip file "/data/app/~~mGI3Zh1ouMWwsDIiPrgS3A==/com.wawavenet.walang-YirlKBWDXdVUSyXG_RUEBg==/base.apk"],nativeLibraryDirectories=[/data/app/~~mGI3Zh1ouMWwsDIiPrgS3A==/com.wawavenet.walang-YirlKBWDXdVUSyXG_RUEBg==/lib/arm64, /data/app/~~mGI3Zh1ouMWwsDIiPrgS3A==/com.wawavenet.walang-YirlKBWDXdVUSyXG_RUEBg==/base.apk!/lib/arm64-v8a, /system/lib64, /product_h/lib64, /system_ext/lib64]]
E/AndroidRuntime(32315): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
E/AndroidRuntime(32315): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(32315): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(32315): 	... 11 more
W/GooglePlayServicesUtil(32315): com.wawavenet.walang requires the Google Play Store, but it is missing.
W/GoogleApiManager(32315): The service for com.google.android.gms.common.internal.service.zap is not available: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}
2
I/ClientTransactionHandler(32315): send EXECUTE_TRANSACTION
I/Process (32315): Sending signal. PID: 32315 SIG: 9
Lost connection to device.
```

**Comment by liranhao** [comment]
排查下是否有同名的class, 或者项目中有引用其他的谷歌SDK，导致了库版本不一致

**Comment by abel-wang-git** [comment]
和mobile_scanner 有冲突
依赖升级下
` implementation 'com.google.mlkit:barcode-scanning:17.2.0'`

Barcode 倒入路径变了

`import com.google.mlkit.vision.barcode.Barcode;`
改为
`import com.google.mlkit.vision.barcode.common.Barcode;`
